# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-05 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='pub_date',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
